// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/dagmar/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Dagmar) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Project *dagger.Directory
	}
	concrete.Project = r.Project
	return json.Marshal(&concrete)
}

func (r *Dagmar) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Project *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Project = concrete.Project
	return nil
}

func (r CognitionRun) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source           *dagger.Directory
		TaskContext      string
		Model            string
		MaxAPICalls      int
		ModuleRef        string
		CoverageFloorBps int
		MaxRevise        int
		CallbackURL      string
		CallbackToken    string
		PromptText       string `json:"prompt_text"`
		GateJSON         string `json:"gate_result"`
		GatePassed       bool   `json:"gate_passed"`
		ReviewJSON       string `json:"review_verdict"`
		Rounds           int    `json:"rounds"`
	}
	concrete.Source = r.Source
	concrete.TaskContext = r.TaskContext
	concrete.Model = r.Model
	concrete.MaxAPICalls = r.MaxAPICalls
	concrete.ModuleRef = r.ModuleRef
	concrete.CoverageFloorBps = r.CoverageFloorBps
	concrete.MaxRevise = r.MaxRevise
	concrete.CallbackURL = r.CallbackURL
	concrete.CallbackToken = r.CallbackToken
	concrete.PromptText = r.PromptText
	concrete.GateJSON = r.GateJSON
	concrete.GatePassed = r.GatePassed
	concrete.ReviewJSON = r.ReviewJSON
	concrete.Rounds = r.Rounds
	return json.Marshal(&concrete)
}

func (r *CognitionRun) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source           *dagger.Directory
		TaskContext      string
		Model            string
		MaxAPICalls      int
		ModuleRef        string
		CoverageFloorBps int
		MaxRevise        int
		CallbackURL      string
		CallbackToken    string
		PromptText       string `json:"prompt_text"`
		GateJSON         string `json:"gate_result"`
		GatePassed       bool   `json:"gate_passed"`
		ReviewJSON       string `json:"review_verdict"`
		Rounds           int    `json:"rounds"`
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	r.TaskContext = concrete.TaskContext
	r.Model = concrete.Model
	r.MaxAPICalls = concrete.MaxAPICalls
	r.ModuleRef = concrete.ModuleRef
	r.CoverageFloorBps = concrete.CoverageFloorBps
	r.MaxRevise = concrete.MaxRevise
	r.CallbackURL = concrete.CallbackURL
	r.CallbackToken = concrete.CallbackToken
	r.PromptText = concrete.PromptText
	r.GateJSON = concrete.GateJSON
	r.GatePassed = concrete.GatePassed
	r.ReviewJSON = concrete.ReviewJSON
	r.Rounds = concrete.Rounds
	return nil
}

func (r Sandbox) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Sandbox) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "CognitionRun":
		switch fnName {
		case "JSON":
			var parent CognitionRun
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CognitionRun).JSON(&parent), nil
		case "Run":
			var parent CognitionRun
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CognitionRun).Run(&parent, ctx)
		case "WithAdjudicate":
			var parent CognitionRun
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CognitionRun).WithAdjudicate(&parent, ctx), nil
		case "WithCode":
			var parent CognitionRun
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CognitionRun).WithCode(&parent, ctx), nil
		case "WithGate":
			var parent CognitionRun
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CognitionRun).WithGate(&parent, ctx), nil
		case "WithPrompt":
			var parent CognitionRun
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var phase string
			if inputArgs["phase"] != nil {
				err = json.Unmarshal([]byte(inputArgs["phase"]), &phase)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg phase", err))
				}
			}
			return (*CognitionRun).WithPrompt(&parent, ctx, phase), nil
		case "WithReview":
			var parent CognitionRun
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CognitionRun).WithReview(&parent, ctx), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Dagmar":
		switch fnName {
		case "Adjudicate":
			var parent Dagmar
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var gateResult string
			if inputArgs["gateResult"] != nil {
				err = json.Unmarshal([]byte(inputArgs["gateResult"]), &gateResult)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg gateResult", err))
				}
			}
			var reviewResult string
			if inputArgs["reviewResult"] != nil {
				err = json.Unmarshal([]byte(inputArgs["reviewResult"]), &reviewResult)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg reviewResult", err))
				}
			}
			var taskContext string
			if inputArgs["taskContext"] != nil {
				err = json.Unmarshal([]byte(inputArgs["taskContext"]), &taskContext)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg taskContext", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			var maxApicalls int
			if inputArgs["maxAPICalls"] != nil {
				err = json.Unmarshal([]byte(inputArgs["maxAPICalls"]), &maxApicalls)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg maxAPICalls", err))
				}
			}
			var moduleRef string
			if inputArgs["moduleRef"] != nil {
				err = json.Unmarshal([]byte(inputArgs["moduleRef"]), &moduleRef)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg moduleRef", err))
				}
			}
			return (*Dagmar).Adjudicate(&parent, ctx, source, gateResult, reviewResult, taskContext, model, maxApicalls, moduleRef)
		case "Code":
			var parent Dagmar
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var promptFile *dagger.File
			if inputArgs["promptFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["promptFile"]), &promptFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg promptFile", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			var maxApicalls int
			if inputArgs["maxAPICalls"] != nil {
				err = json.Unmarshal([]byte(inputArgs["maxAPICalls"]), &maxApicalls)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg maxAPICalls", err))
				}
			}
			var moduleRef string
			if inputArgs["moduleRef"] != nil {
				err = json.Unmarshal([]byte(inputArgs["moduleRef"]), &moduleRef)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg moduleRef", err))
				}
			}
			return (*Dagmar).Code(&parent, ctx, source, promptFile, model, maxApicalls, moduleRef)
		case "CognitionRun":
			var parent Dagmar
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var taskContext string
			if inputArgs["taskContext"] != nil {
				err = json.Unmarshal([]byte(inputArgs["taskContext"]), &taskContext)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg taskContext", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			var maxApicalls int
			if inputArgs["maxAPICalls"] != nil {
				err = json.Unmarshal([]byte(inputArgs["maxAPICalls"]), &maxApicalls)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg maxAPICalls", err))
				}
			}
			var moduleRef string
			if inputArgs["moduleRef"] != nil {
				err = json.Unmarshal([]byte(inputArgs["moduleRef"]), &moduleRef)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg moduleRef", err))
				}
			}
			var coverageFloorBps int
			if inputArgs["coverageFloorBps"] != nil {
				err = json.Unmarshal([]byte(inputArgs["coverageFloorBps"]), &coverageFloorBps)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg coverageFloorBps", err))
				}
			}
			var maxRevise int
			if inputArgs["maxRevise"] != nil {
				err = json.Unmarshal([]byte(inputArgs["maxRevise"]), &maxRevise)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg maxRevise", err))
				}
			}
			var callbackUrl string
			if inputArgs["callbackURL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["callbackURL"]), &callbackUrl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg callbackURL", err))
				}
			}
			var callbackToken string
			if inputArgs["callbackToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["callbackToken"]), &callbackToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg callbackToken", err))
				}
			}
			return (*Dagmar).CognitionRun(&parent, source, taskContext, model, maxApicalls, moduleRef, coverageFloorBps, maxRevise, callbackUrl, callbackToken), nil
		case "Diff":
			var parent Dagmar
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var after *dagger.Directory
			if inputArgs["after"] != nil {
				err = json.Unmarshal([]byte(inputArgs["after"]), &after)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg after", err))
				}
			}
			var before *dagger.Directory
			if inputArgs["before"] != nil {
				err = json.Unmarshal([]byte(inputArgs["before"]), &before)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg before", err))
				}
			}
			return (*Dagmar).Diff(&parent, ctx, after, before), nil
		case "Prompt":
			var parent Dagmar
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var phase string
			if inputArgs["phase"] != nil {
				err = json.Unmarshal([]byte(inputArgs["phase"]), &phase)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg phase", err))
				}
			}
			var taskContext string
			if inputArgs["taskContext"] != nil {
				err = json.Unmarshal([]byte(inputArgs["taskContext"]), &taskContext)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg taskContext", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			var maxApicalls int
			if inputArgs["maxAPICalls"] != nil {
				err = json.Unmarshal([]byte(inputArgs["maxAPICalls"]), &maxApicalls)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg maxAPICalls", err))
				}
			}
			var moduleRef string
			if inputArgs["moduleRef"] != nil {
				err = json.Unmarshal([]byte(inputArgs["moduleRef"]), &moduleRef)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg moduleRef", err))
				}
			}
			return (*Dagmar).Prompt(&parent, ctx, source, phase, taskContext, model, maxApicalls, moduleRef)
		case "Review":
			var parent Dagmar
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var promptFile *dagger.File
			if inputArgs["promptFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["promptFile"]), &promptFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg promptFile", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			var maxApicalls int
			if inputArgs["maxAPICalls"] != nil {
				err = json.Unmarshal([]byte(inputArgs["maxAPICalls"]), &maxApicalls)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg maxAPICalls", err))
				}
			}
			var moduleRef string
			if inputArgs["moduleRef"] != nil {
				err = json.Unmarshal([]byte(inputArgs["moduleRef"]), &moduleRef)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg moduleRef", err))
				}
			}
			return (*Dagmar).Review(&parent, ctx, source, promptFile, model, maxApicalls, moduleRef)
		case "Sandbox":
			var parent Dagmar
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var image string
			if inputArgs["image"] != nil {
				err = json.Unmarshal([]byte(inputArgs["image"]), &image)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg image", err))
				}
			}
			var workingDir string
			if inputArgs["workingDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workingDir"]), &workingDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workingDir", err))
				}
			}
			return (*Dagmar).Sandbox(&parent, image, workingDir)
		case "":
			var parent Dagmar
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var project *dagger.Directory
			if inputArgs["project"] != nil {
				err = json.Unmarshal([]byte(inputArgs["project"]), &project)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg project", err))
				}
			}
			return New(project), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Sandbox":
		switch fnName {
		case "Container":
			var parent Sandbox
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Sandbox).Container(&parent), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
