// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Dagmar
func (r *Binding) AsDagmar() *Dagmar { // dagmar (../../../.dagmar/main.go:22:6)
	q := r.query.Select("asDagmar")

	return &Dagmar{
		query: q,
	}
}

// Dagmar is dagmar-as-a-Project's main Dagger object (ADR-0014). It carries the Project source
// as bound state for the LLM-Tool hooks (dagmar-issues, dagmar-memory), which need it to build
// containers with the workspace mounted. The gate-family methods still take source explicitly.
type Dagmar struct { // dagmar (../../../.dagmar/main.go:22:6)
	query *querybuilder.Selection

	dagmarBootstrap *string
	dagmarGate      *string
	dagmarIssues    *string
	dagmarMemory    *string
	id              *ID
}

func (r *Dagmar) WithGraphQLQuery(q *querybuilder.Selection) *Dagmar {
	return &Dagmar{
		query: q,
	}
}

// DagmarDagmarBootstrapOpts contains options for Dagmar.DagmarBootstrap
type DagmarDagmarBootstrapOpts struct {
	//
	// githubToken authenticates ubi GitHub-API calls (avoids rate-limiting). Optional: nil = unauthenticated.
	// Pass via `--github-token env:GITHUB_TOKEN` (dagger reads from the local environment as a Secret).
	//
	GithubToken *Secret // dagmar (../../../.dagmar/main.go:41:2)
}

// DagmarBootstrap is dagmar's gate-family PREPARE step (ADR-0009 §2 / ADR-0012 §4): an
// always-Dagger function that rolls out the Project's mise toolchain (mise.toml) into the gate
// container before verification. Run once per workspace — by CI, lefthook pre-push, or the agent
// setup. The method name exposes as the dagger function `dagmar-bootstrap` (the
// conformance-contract name; kebab-cased by the Go SDK). Delegates to workflows.
func (r *Dagmar) DagmarBootstrap(ctx context.Context, source *Directory, opts ...DagmarDagmarBootstrapOpts) (string, error) { // dagmar (../../../.dagmar/main.go:34:1)
	assertNotNil("source", source)
	if r.dagmarBootstrap != nil {
		return *r.dagmarBootstrap, nil
	}
	q := r.query.Select("dagmarBootstrap")
	for i := len(opts) - 1; i >= 0; i-- {
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
	}
	q = q.Arg("source", source)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// DagmarDagmarGateOpts contains options for Dagmar.DagmarGate
type DagmarDagmarGateOpts struct {
	//
	// githubToken authenticates ubi GitHub-API calls (avoids rate-limiting). Optional: nil = unauthenticated.
	// Pass via `--github-token env:GITHUB_TOKEN` (dagger reads from the local environment as a Secret).
	//
	GithubToken *Secret // dagmar (../../../.dagmar/main.go:58:2)
	//
	// coverageFloorBps is the ratcheted coverage floor in basis points (0–10000, e.g. 7850 = 78.50%).
	// When > 0, the gate measures total go test coverage and fails if below the floor (dagmar-4154).
	// 0 = coverage check disabled.
	//
	CoverageFloorBps int // dagmar (../../../.dagmar/main.go:64:2)
}

// DagmarGate is dagmar's gate-family VERIFY step (ADR-0009 §2 / ADR-0012 §4 / ADR-0017 §3):
// an always-Dagger function with hard-coded Go checkables (NOT YAML manifest). The check logic —
// build, vet, test, gofmt, secret scan, coverage — lives entirely in Go code inside the gate
// function. Reused in CI (`dagger call -m .dagmar dagmar-gate --source .`) AND in-loop (coder
// self-verification, Phase 2). Exposes as the dagger function `dagmar-gate`. Delegates to workflows.
func (r *Dagmar) DagmarGate(ctx context.Context, source *Directory, opts ...DagmarDagmarGateOpts) (string, error) { // dagmar (../../../.dagmar/main.go:51:1)
	assertNotNil("source", source)
	if r.dagmarGate != nil {
		return *r.dagmarGate, nil
	}
	q := r.query.Select("dagmarGate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
		// `coverageFloorBps` optional argument
		if !querybuilder.IsZeroValue(opts[i].CoverageFloorBps) {
			q = q.Arg("coverageFloorBps", opts[i].CoverageFloorBps)
		}
	}
	q = q.Arg("source", source)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// DagmarDagmarIssuesOpts contains options for Dagmar.DagmarIssues
type DagmarDagmarIssuesOpts struct {
	//
	// id: issue identifier (for read/update).
	//
	ID string // dagmar (../../../.dagmar/main.go:82:2)
	//
	// query: search text (for search).
	//
	Query string // dagmar (../../../.dagmar/main.go:85:2)
	//
	// title: issue title (for create).
	//
	Title string // dagmar (../../../.dagmar/main.go:88:2)
	//
	// body: issue body (for create/update).
	//
	Body string // dagmar (../../../.dagmar/main.go:91:2)
}

// DagmarIssues is dagmar's issue-tracker LLM-Tool hook (ADR-0019 D2 / ADR-0017 §2).
// Registered via Env.WithMainModule() and called by the LLM as a native Dagger tool during the
// loop. The LLM uses it to read, search, create, and update issues in the project's tracker
// (seeds). Delegates to workflows.DagmarIssues.
//
// Operates on the project worktree implicitly (ADR-0019 D2) — no source parameter. The backing
// CLI (sd) reads .seeds/ from the current working directory.
func (r *Dagmar) DagmarIssues(ctx context.Context, action string, opts ...DagmarDagmarIssuesOpts) (string, error) { // dagmar (../../../.dagmar/main.go:76:1)
	if r.dagmarIssues != nil {
		return *r.dagmarIssues, nil
	}
	q := r.query.Select("dagmarIssues")
	for i := len(opts) - 1; i >= 0; i-- {
		// `id` optional argument
		if !querybuilder.IsZeroValue(opts[i].ID) {
			q = q.Arg("id", opts[i].ID)
		}
		// `query` optional argument
		if !querybuilder.IsZeroValue(opts[i].Query) {
			q = q.Arg("query", opts[i].Query)
		}
		// `title` optional argument
		if !querybuilder.IsZeroValue(opts[i].Title) {
			q = q.Arg("title", opts[i].Title)
		}
		// `body` optional argument
		if !querybuilder.IsZeroValue(opts[i].Body) {
			q = q.Arg("body", opts[i].Body)
		}
	}
	q = q.Arg("action", action)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// DagmarDagmarMemoryOpts contains options for Dagmar.DagmarMemory
type DagmarDagmarMemoryOpts struct {
	//
	// query: expertise query or domain (for read/search).
	//
	Query string // dagmar (../../../.dagmar/main.go:113:2)
	//
	// key: record key/domain (for write).
	//
	Key string // dagmar (../../../.dagmar/main.go:116:2)
	//
	// value: expertise content (for write).
	//
	Value string // dagmar (../../../.dagmar/main.go:119:2)
}

// DagmarMemory is dagmar's expertise-store LLM-Tool hook (ADR-0019 D2 / ADR-0017 §2).
// Registered via Env.WithMainModule() and called by the LLM as a native Dagger tool during the
// loop. The LLM uses it to read, search, and write project expertise (mulch). Delegates to
// workflows.DagmarMemory.
//
// Operates on the project worktree implicitly (ADR-0019 D2) — no source parameter. The backing
// CLI (ml) reads .mulch/ from the current working directory.
func (r *Dagmar) DagmarMemory(ctx context.Context, action string, opts ...DagmarDagmarMemoryOpts) (string, error) { // dagmar (../../../.dagmar/main.go:107:1)
	if r.dagmarMemory != nil {
		return *r.dagmarMemory, nil
	}
	q := r.query.Select("dagmarMemory")
	for i := len(opts) - 1; i >= 0; i-- {
		// `query` optional argument
		if !querybuilder.IsZeroValue(opts[i].Query) {
			q = q.Arg("query", opts[i].Query)
		}
		// `key` optional argument
		if !querybuilder.IsZeroValue(opts[i].Key) {
			q = q.Arg("key", opts[i].Key)
		}
		// `value` optional argument
		if !querybuilder.IsZeroValue(opts[i].Value) {
			q = q.Arg("value", opts[i].Value)
		}
	}
	q = q.Arg("action", action)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this Dagmar.
func (r *Dagmar) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Dagmar) XXX_GraphQLType() string {
	return "Dagmar"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Dagmar) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Dagmar) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Dagmar) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Dagmar) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Dagmar{query: selectNode(dag.query, id, "Dagmar")}
	return nil
}

// AsNode returns this Dagmar as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Dagmar) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Create or update a binding of type Dagmar in the environment
func (r *Env) WithDagmarInput(name string, value *Dagmar, description string) *Env { // dagmar (../../../.dagmar/main.go:22:6)
	assertNotNil("value", value)
	q := r.query.Select("withDagmarInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Dagmar output to be assigned in the environment
func (r *Env) WithDagmarOutput(name string, description string) *Env { // dagmar (../../../.dagmar/main.go:22:6)
	q := r.query.Select("withDagmarOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Dagmar is dagmar-as-a-Project's main Dagger object (ADR-0014). It carries the Project source
// as bound state for the LLM-Tool hooks (dagmar-issues, dagmar-memory), which need it to build
// containers with the workspace mounted. The gate-family methods still take source explicitly.
func (r *Query) Dagmar() *Dagmar { // dagmar (../../../.dagmar/main.go:22:6)
	q := r.query.Select("dagmar")

	return &Dagmar{
		query: q,
	}
}
