// Code generated by MockGen. DO NOT EDIT.
// Source: oseco.go
//
// Generated by this command:
//
//	mockgen -source=oseco.go -destination=mock_oseco.go -package=ports
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIssueTracker is a mock of IssueTracker interface.
type MockIssueTracker struct {
	ctrl     *gomock.Controller
	recorder *MockIssueTrackerMockRecorder
	isgomock struct{}
}

// MockIssueTrackerMockRecorder is the mock recorder for MockIssueTracker.
type MockIssueTrackerMockRecorder struct {
	mock *MockIssueTracker
}

// NewMockIssueTracker creates a new mock instance.
func NewMockIssueTracker(ctrl *gomock.Controller) *MockIssueTracker {
	mock := &MockIssueTracker{ctrl: ctrl}
	mock.recorder = &MockIssueTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueTracker) EXPECT() *MockIssueTrackerMockRecorder {
	return m.recorder
}

// CreateIssue mocks base method.
func (m *MockIssueTracker) CreateIssue(ctx context.Context, title, body string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIssue", ctx, title, body)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIssue indicates an expected call of CreateIssue.
func (mr *MockIssueTrackerMockRecorder) CreateIssue(ctx, title, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIssue", reflect.TypeOf((*MockIssueTracker)(nil).CreateIssue), ctx, title, body)
}

// MockMemory is a mock of Memory interface.
type MockMemory struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryMockRecorder
	isgomock struct{}
}

// MockMemoryMockRecorder is the mock recorder for MockMemory.
type MockMemoryMockRecorder struct {
	mock *MockMemory
}

// NewMockMemory creates a new mock instance.
func NewMockMemory(ctrl *gomock.Controller) *MockMemory {
	mock := &MockMemory{ctrl: ctrl}
	mock.recorder = &MockMemoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemory) EXPECT() *MockMemoryMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockMemory) Read(ctx context.Context, query string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockMemoryMockRecorder) Read(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockMemory)(nil).Read), ctx, query)
}

// MockPrompts is a mock of Prompts interface.
type MockPrompts struct {
	ctrl     *gomock.Controller
	recorder *MockPromptsMockRecorder
	isgomock struct{}
}

// MockPromptsMockRecorder is the mock recorder for MockPrompts.
type MockPromptsMockRecorder struct {
	mock *MockPrompts
}

// NewMockPrompts creates a new mock instance.
func NewMockPrompts(ctrl *gomock.Controller) *MockPrompts {
	mock := &MockPrompts{ctrl: ctrl}
	mock.recorder = &MockPromptsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompts) EXPECT() *MockPromptsMockRecorder {
	return m.recorder
}

// Compose mocks base method.
func (m *MockPrompts) Compose(ctx context.Context, agent string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compose", ctx, agent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compose indicates an expected call of Compose.
func (mr *MockPromptsMockRecorder) Compose(ctx, agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compose", reflect.TypeOf((*MockPrompts)(nil).Compose), ctx, agent)
}

// MockTracer is a mock of Tracer interface.
type MockTracer struct {
	ctrl     *gomock.Controller
	recorder *MockTracerMockRecorder
	isgomock struct{}
}

// MockTracerMockRecorder is the mock recorder for MockTracer.
type MockTracerMockRecorder struct {
	mock *MockTracer
}

// NewMockTracer creates a new mock instance.
func NewMockTracer(ctrl *gomock.Controller) *MockTracer {
	mock := &MockTracer{ctrl: ctrl}
	mock.recorder = &MockTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracer) EXPECT() *MockTracerMockRecorder {
	return m.recorder
}

// StartSpan mocks base method.
func (m *MockTracer) StartSpan(ctx context.Context, name string) (context.Context, Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSpan", ctx, name)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(Span)
	return ret0, ret1
}

// StartSpan indicates an expected call of StartSpan.
func (mr *MockTracerMockRecorder) StartSpan(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSpan", reflect.TypeOf((*MockTracer)(nil).StartSpan), ctx, name)
}

// MockSpan is a mock of Span interface.
type MockSpan struct {
	ctrl     *gomock.Controller
	recorder *MockSpanMockRecorder
	isgomock struct{}
}

// MockSpanMockRecorder is the mock recorder for MockSpan.
type MockSpanMockRecorder struct {
	mock *MockSpan
}

// NewMockSpan creates a new mock instance.
func NewMockSpan(ctrl *gomock.Controller) *MockSpan {
	mock := &MockSpan{ctrl: ctrl}
	mock.recorder = &MockSpanMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpan) EXPECT() *MockSpanMockRecorder {
	return m.recorder
}

// End mocks base method.
func (m *MockSpan) End() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "End")
}

// End indicates an expected call of End.
func (mr *MockSpanMockRecorder) End() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockSpan)(nil).End))
}
